# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "vios.ai: life, artificial intelligence"
#author: Laurent Demailly
description: > # this means to ignore newlines until "baseurl:"
 <a href="http://vios.ai/">vios.ai</a> - welcome to vios.ai
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vios.ai/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vios_ai
github_username:  vios-ai
email: info@vios.ai
#google_analytics: UA-103018328-1
#facebook:
#  appid: 337741350005511

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
